# 맛이 어떤데?
version: "3"
services: 
#     react-app-nolshimung:
#         image: wnsrb003/react-app-nolshimung:latest
        # build: ./FE
#         stdin_open: true
#         ports: 
#             - "3000:3000"
#             - "443:3000"
        # networks: 
        #     - mern-app
    api-server-nolshimung:
        image: wnsrb003/api-server-nolshimung:latest
        restart: always
        volumes:
            - ./nolmungshimung.shop:/app/ssl
        ports:
            - "8443:8443"
            - "7889:7889"
            - "3001:3001"
            - "3003:3003"
        image: redis
 
    mongo:
       image: mongo
       ports:
           - "27017:27017"
        # networks: 
        #     - mern-app
       volumes:
           - ./mongo-data:/data/db
       environment:
        # MongoDB 계정 및 패스워드 설정 옵션
         MONGO_INITDB_ROOT_USERNAME: ${mongo_user}
         MONGO_INITDB_ROOT_PASSWORD: ${mongo_passwd}
    # networks: 
    #     mern-app:
    #         driver: bridge
    # volumes: 
    #     mongo-data:
    #         driver: local
