# 맛이 어떤데?
version: "3"
services: 
    react-app-nolshimung:
        image: wnsrb003/react-app-nolshimung:latest
        # build: ./FE
        stdin_open: true
        ports: 
            - "3000:3000"
            - "443:3000"
        # networks: 
        #     - mern-app
    api-server-nolshimung:
        image: wnsrb003/api-server-nolshimung:latest
        # build: ./BE
        ports:
            - "8443:8443"
            - "7889:7889"
            - "3001:3001"
            - "3003:3003"
    redis_boot:
        image: redis:alpine
        command: redis-server --port 6379
#         container_name: redis_boot
#         hostname: redis_boot
#         labels: 
#             - "name=redis"
#             - "mode=standalone"
        ports: 
            - 6379:6379
        # links: 
        #     - mongo
        # depends_on: 
        #     - mongo
        # networks: 
        #     - mern-app    
    # mongo:
    #     image: mongo
    #     ports: 
    #         - "27017:27017"
        # networks: 
        #     - mern-app
        # volumes: 
        #     - mongo-data:/Users/gyu/Documents/db
    # networks: 
    #     mern-app:
    #         driver: bridge
    # volumes: 
    #     mongo-data:
    #         driver: local
