name: Docker

## 바뀌는가?
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "master" ]
    # Publish semver tags as releases.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: react Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./FE/Dockerfile 
          platforms: linux/amd64
          push: true
          tags: wnsrb003/react-app-nolshimung:latest
      -
        name: api-server Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./BE/Dockerfile 
          platforms: linux/amd64
          push: true
          tags: wnsrb003/api-server-nolshimung:latest
  Deploy:
    needs: build
    name: continuos deploy
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          password: ${{ secrets.PASSWD }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/"
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          password: ${{ secrets.PASSWD }}
          host: ${{ secrets.HOST }}
          username: ubuntu
          script: |
            sudo docker-compose down && 
            sudo docker-compose pull && 
            sudo docker-compose up -d
