name: Docker

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "develop" ]
    # Publish semver tags as releases.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: wnsrb003/api-server-nolshimung
          
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      -
        name: react Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./FE/Dockerfile 
          platforms: linux/amd64
          push: true
          
      -
        name: api-server Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./BE/Dockerfile 
          platforms: linux/amd64
          push: true
